/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cic.unb.bd.GUI;
import javax.swing.*;
import java.awt.event.*;

/**
 *
 * @author macel
 */
public class GraphicInterface extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2037495145957961599L;
	/**
     * Creates new form GraphicInterface
     */
    public GraphicInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WarningFrame = new javax.swing.JFrame();
        WarningInternalFrame = new javax.swing.JInternalFrame();
        WarnButton = new javax.swing.JButton();
        WarnText = new javax.swing.JLabel();
        InternalFrame = new javax.swing.JInternalFrame();
        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        QueryMenu = new javax.swing.JMenu();
        Query1 = new javax.swing.JMenuItem();
        Query2 = new javax.swing.JMenuItem();
        Query3 = new javax.swing.JMenuItem();
        Query4 = new javax.swing.JMenuItem();
        Query5 = new javax.swing.JMenuItem();
        QueryGenOPT = new javax.swing.JMenuItem();

        WarningInternalFrame.setVisible(true);

        WarnButton.setText("OK");
        WarnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKWarnActionPerformed(evt);
            }
        });

        WarnText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        WarnText.setText("jLabel1");

        javax.swing.GroupLayout WarningInternalFrameLayout = new javax.swing.GroupLayout(WarningInternalFrame.getContentPane());
        WarningInternalFrame.getContentPane().setLayout(WarningInternalFrameLayout);
        WarningInternalFrameLayout.setHorizontalGroup(
            WarningInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarningInternalFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(WarnButton))
            .addGroup(WarningInternalFrameLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(WarnText, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        WarningInternalFrameLayout.setVerticalGroup(
            WarningInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarningInternalFrameLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(WarnText, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WarnButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout WarningFrameLayout = new javax.swing.GroupLayout(WarningFrame.getContentPane());
        WarningFrame.getContentPane().setLayout(WarningFrameLayout);
        WarningFrameLayout.setHorizontalGroup(
            WarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarningInternalFrame)
        );
        WarningFrameLayout.setVerticalGroup(
            WarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarningInternalFrame)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InternalFrame.setVisible(true);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane.setViewportView(Table);

        QueryMenu.setText("Querys");

        Query1.setText("Query1");
        Query1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(Query1);

        Query2.setText("Query2");
        Query2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(Query2);

        Query3.setText("Query3");
        Query3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(Query3);

        Query4.setText("Query4");
        Query4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(Query4);

        Query5.setText("Query5");
        Query5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(Query5);

        QueryGenOPT.setText("Query Generica");
        QueryGenOPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueryActionPerformed(evt);
            }
        });
        QueryMenu.add(QueryGenOPT);

        Menu.add(QueryMenu);

        InternalFrame.setJMenuBar(Menu);

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame.getContentPane());
        InternalFrame.getContentPane().setLayout(InternalFrameLayout);
        InternalFrameLayout.setHorizontalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        InternalFrameLayout.setVerticalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QueryActionPerformed(java.awt.event.ActionEvent evt) {                                       
        if(evt.getSource().equals(Query1)){
        }
        else if(evt.getSource().equals(Query2)){

        }
        else if(evt.getSource().equals(Query3)){

        }
        else if(evt.getSource().equals(Query4)){
  
        }
        else if(evt.getSource().equals(Query5)){

        }
        else if(evt.getSource().equals(QueryGenOPT)){

        }
    }                                                                    
    
    private void OKWarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query2ActionPerformed

    }//GEN-LAST:event_Query2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Query1;
    private javax.swing.JMenuItem Query2;
    private javax.swing.JMenuItem Query3;
    private javax.swing.JMenuItem Query4;
    private javax.swing.JMenuItem Query5;
    private javax.swing.JMenuItem QueryGenOPT;
    private javax.swing.JMenu QueryMenu;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Table;
    private javax.swing.JButton WarnButton;
    private javax.swing.JLabel WarnText;
    private javax.swing.JFrame WarningFrame;
    private javax.swing.JInternalFrame WarningInternalFrame;
    // End of variables declaration//GEN-END:variables
}
