/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.cic.unb.bd.GUI;

/**
 *
 * @author macel
 */
public class GraphicInterface extends javax.swing.JFrame {

    /**
     * Creates new form GraphicInterface
     */
    public GraphicInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenericQuery = new javax.swing.JDialog();
        GenQueryFrame = new javax.swing.JInternalFrame();
        GenQueryText = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        Warnig = new javax.swing.JDialog();
        WarnFrame = new javax.swing.JInternalFrame();
        WarningText = new javax.swing.JLabel();
        OKButtonWarn = new javax.swing.JButton();
        InternalFrame = new javax.swing.JInternalFrame();
        ScrollPane = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Menu = new javax.swing.JMenuBar();
        QueryMenu = new javax.swing.JMenu();
        Query1 = new javax.swing.JMenuItem();
        Query2 = new javax.swing.JMenuItem();
        Query3 = new javax.swing.JMenuItem();
        Query4 = new javax.swing.JMenuItem();
        Query5 = new javax.swing.JMenuItem();
        QueryGenOPT = new javax.swing.JMenuItem();

        GenQueryFrame.setVisible(true);

        GenQueryText.setText("Query");

        OKButton.setText("OK");

        javax.swing.GroupLayout GenQueryFrameLayout = new javax.swing.GroupLayout(GenQueryFrame.getContentPane());
        GenQueryFrame.getContentPane().setLayout(GenQueryFrameLayout);
        GenQueryFrameLayout.setHorizontalGroup(
            GenQueryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenQueryFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GenQueryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GenQueryText)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GenQueryFrameLayout.createSequentialGroup()
                        .addGap(0, 324, Short.MAX_VALUE)
                        .addComponent(OKButton)))
                .addContainerGap())
        );
        GenQueryFrameLayout.setVerticalGroup(
            GenQueryFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GenQueryFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GenQueryText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OKButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GenericQueryLayout = new javax.swing.GroupLayout(GenericQuery.getContentPane());
        GenericQuery.getContentPane().setLayout(GenericQueryLayout);
        GenericQueryLayout.setHorizontalGroup(
            GenericQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GenQueryFrame)
        );
        GenericQueryLayout.setVerticalGroup(
            GenericQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GenQueryFrame)
        );

        WarnFrame.setVisible(true);

        WarningText.setText("Warning");

        OKButtonWarn.setText("OK");

        javax.swing.GroupLayout WarnFrameLayout = new javax.swing.GroupLayout(WarnFrame.getContentPane());
        WarnFrame.getContentPane().setLayout(WarnFrameLayout);
        WarnFrameLayout.setHorizontalGroup(
            WarnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WarnFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OKButtonWarn)
                .addContainerGap())
            .addGroup(WarnFrameLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(WarningText, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        WarnFrameLayout.setVerticalGroup(
            WarnFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WarnFrameLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(WarningText, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OKButtonWarn)
                .addContainerGap())
        );

        javax.swing.GroupLayout WarnigLayout = new javax.swing.GroupLayout(Warnig.getContentPane());
        Warnig.getContentPane().setLayout(WarnigLayout);
        WarnigLayout.setHorizontalGroup(
            WarnigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarnFrame)
        );
        WarnigLayout.setVerticalGroup(
            WarnigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarnFrame)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InternalFrame.setVisible(true);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane.setViewportView(Table);

        QueryMenu.setText("Querys");

        Query1.setText("Query1");
        QueryMenu.add(Query1);

        Query2.setText("Query2");
        Query2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Query2ActionPerformed(evt);
            }
        });
        QueryMenu.add(Query2);

        Query3.setText("Query3");
        QueryMenu.add(Query3);

        Query4.setText("Query4");
        QueryMenu.add(Query4);

        Query5.setText("Query5");
        QueryMenu.add(Query5);

        QueryGenOPT.setText("Query Generica");
        QueryMenu.add(QueryGenOPT);

        Menu.add(QueryMenu);

        InternalFrame.setJMenuBar(Menu);

        javax.swing.GroupLayout InternalFrameLayout = new javax.swing.GroupLayout(InternalFrame.getContentPane());
        InternalFrame.getContentPane().setLayout(InternalFrameLayout);
        InternalFrameLayout.setHorizontalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addContainerGap())
        );
        InternalFrameLayout.setVerticalGroup(
            InternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InternalFrame)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Query2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Query2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Query2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame GenQueryFrame;
    private javax.swing.JTextField GenQueryText;
    private javax.swing.JDialog GenericQuery;
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton OKButtonWarn;
    private javax.swing.JMenuItem Query1;
    private javax.swing.JMenuItem Query2;
    private javax.swing.JMenuItem Query3;
    private javax.swing.JMenuItem Query4;
    private javax.swing.JMenuItem Query5;
    private javax.swing.JMenuItem QueryGenOPT;
    private javax.swing.JMenu QueryMenu;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTable Table;
    private javax.swing.JInternalFrame WarnFrame;
    private javax.swing.JDialog Warnig;
    private javax.swing.JLabel WarningText;
    // End of variables declaration//GEN-END:variables
}
