copy public.org_superior from 'path_to_directory/ORG_SUPERIOR.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.org_subordinado from 'path_to_directory/ORG_SUBORDINADO.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.pessoa from 'path_to_directory/PESSOA.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.funcao from 'path_to_directory/FUNCAO.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.unidade_gestora from 'path_to_directory/UNIDADE_GESTORA.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.subfuncao from 'path_to_directory/SUBFUNCAO.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.programa from 'path_to_directory/PROGRAMA.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.acao from 'path_to_directory/ACAO.csv' with (FORMAT csv, DELIMITER E'\t');
copy public.docpag from 'path_to_directory/DOCPAG.csv' with (FORMAT csv, DELIMITER E'\t');
